### ISSUE TITLE
cant run main.py 

### ISSUE THREAD

**Issue by M1noa** [MrRazamataz/MCRewards-Discord-Bot#1]
I have python and pip installed I followed the instructions on GitHub I installed requirements.txt this is the error I got in pycharm when I tried also running it in it

Starting up...
[MCRewards] Loaded cog
[MCRewards] Loaded cog
[MCRewards] Loaded cog
Traceback (most recent call last):
  File "C:\Users\baccu\Desktop\MCRewards-Discord-Bot-main\main.py", line 40, in <module>
    client.run(token)
  File "C:\Users\baccu\Desktop\MCRewards-Discord-Bot-main\venv\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\baccu\Desktop\MCRewards-Discord-Bot-main\venv\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\baccu\Desktop\MCRewards-Discord-Bot-main\venv\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\baccu\Desktop\MCRewards-Discord-Bot-main\venv\lib\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020770EF79A0>
Traceback (most recent call last):
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020770EF79A0>
Traceback (most recent call last):
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\baccu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 1

**Comment by MrRazamataz** [comment]
Hey @MinoaBaccus , sorry, please use the latest `main.py` in the repo. 

The issue was I set the bot to use permission intents, but its not really needed for this bot, so i have removed and it should be fine now.

**Comment by MrRazamataz** [comment]
Closed due to no response, assumed fixed.
